#!/bin/bash
#usage:
#$1: the existing casename
#$2: the desired casename
for file in $(ls *$1*.sum && ls *$1*.dat && ls *$1*.zones )
do
    #echo ${file##*full_room}
    mv $file "${file//$1/$2}"
done